spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${PASSWORD:postgres}
    username: ${USERNAME:postgres}
    url: jdbc:postgresql://${HOST:localhost}:${POSTGRES_PORT:5432}/hursa_knives?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 50MB
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    org.springframework.security: TRACE
    blog: WARN

server:
  port: ${PORT:8080}

hursa:
  admin:
    email: ${ADMIN_EMAIL:admin@hursa.com}
    password: ${ADMIN_PASSWORD:admin}
  rememberme:
    key: ${REMEMBER_ME_KEY:secret}

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME:hursa-knives}
  apiKey: ${CLOUDINARY_API_KEY:123456789}
  apiSecret: ${CLOUDINARY_API_SECRET:123456789}

